# -*- coding: utf-8 -*-
"""Script_methode_classification.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lgO46Fei8NZPyn9gF_eNlBAE2aAXZYSt
"""

def classify_accident(inf_accident, method, model = None):
    if method != None:
        prediction = model.predict([inf_accident])['descr_grav']
    
    else:
        return json.dumps({'error': 'Methode non prise en charge'})
    
    return json.dumps({'descr_grav': prediction})